import os
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()
MONGODB_URI = os.getenv("MONGODB_URI", "mongodb+srv://deepbuddhadev135_db_user:RFUtAgSlhuwoDLRg@rms.beog0b4.mongodb.net/healthconnect?retryWrites=true&w=majority")
c = MongoClient(MONGODB_URI)
db = c['healthconnect']

all_hospitals = [
  {
    'id': 'fac_civil_01',
    'facilityId': 'fac_civil_01',
    'name': 'Gandhinagar Civil Hospital & Medical College',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Gandhinagar',
    'state': 'Gujarat',
    'address': 'Sector 12, Near Bus Depot, Gandhinagar - 382012',
    'pincode': '382012',
    'contactNumber': '079-2322-1916',
    'phone': '079-2322-1916',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.2156, 'lng': 72.6369},
    'latitude': 23.2156,
    'longitude': 72.6369,
    'location': {'type': 'Point', 'coordinates': [72.6369, 23.2156]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 15,
    'totalBeds': 650,
    'availableBeds': 84,
    'icuBedsTotal': 60,
    'icuBedsAvailable': 12,
    'specialties': ['General Medicine', 'Cardiology', 'Orthopedics', 'Pediatrics', 'Obstetrics & Gynecology']
  },
  {
    'id': 'fac_mansa_02',
    'facilityId': 'fac_mansa_02',
    'name': 'Mansa Community Health Centre (CHC)',
    'type': 'CHC',
    'district': 'Gandhinagar',
    'state': 'Gujarat',
    'address': 'Station Road, Mansa, Gandhinagar - 382845',
    'pincode': '382845',
    'contactNumber': '02763-272020',
    'phone': '02763-272020',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.4281, 'lng': 72.6612},
    'latitude': 23.4281,
    'longitude': 72.6612,
    'location': {'type': 'Point', 'coordinates': [72.6612, 23.4281]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 15,
    'totalBeds': 50,
    'availableBeds': 18,
    'icuBedsTotal': 4,
    'icuBedsAvailable': 2,
    'specialties': ['General Medicine', 'General Surgery', 'Obstetrics & Gynecology', 'Pediatrics']
  },
  {
    'id': 'fac_kalol_03',
    'facilityId': 'fac_kalol_03',
    'name': 'Kalol Sub-District Hospital',
    'type': 'SUB_DISTRICT_HOSPITAL',
    'district': 'Gandhinagar',
    'state': 'Gujarat',
    'address': 'Vakharia Chowk, Kalol, Gandhinagar - 382721',
    'pincode': '382721',
    'contactNumber': '02764-222100',
    'phone': '02764-222100',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.2372, 'lng': 72.4984},
    'latitude': 23.2372,
    'longitude': 72.4984,
    'location': {'type': 'Point', 'coordinates': [72.4984, 23.2372]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 10,
    'totalBeds': 100,
    'availableBeds': 22,
    'icuBedsTotal': 8,
    'icuBedsAvailable': 3,
    'specialties': ['General Medicine', 'General Surgery', 'Pediatrics']
  },
  {
    'id': 'fac_pet_04',
    'facilityId': 'fac_pet_04',
    'name': 'Pethapur Primary Health Centre (PHC)',
    'type': 'PHC',
    'district': 'Gandhinagar',
    'state': 'Gujarat',
    'address': 'Near Old Gram Panchayat, Pethapur - 382610',
    'pincode': '382610',
    'contactNumber': '079-2328-7010',
    'phone': '079-2328-7010',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.2721, 'lng': 72.6841},
    'latitude': 23.2721,
    'longitude': 72.6841,
    'location': {'type': 'Point', 'coordinates': [72.6841, 23.2721]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': False,
    'currentWaitTimeMinutes': 8,
    'totalBeds': 12,
    'availableBeds': 7,
    'icuBedsTotal': 0,
    'icuBedsAvailable': 0,
    'specialties': ['General OPD', 'Maternal & Child Health', 'Immunization']
  },
  {
    'id': 'fac_raj_civil_01',
    'facilityId': 'fac_raj_civil_01',
    'name': 'PDU Government Medical College & Civil Hospital',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Rajkot',
    'state': 'Gujarat',
    'address': 'Hospital Chowk, Rajkot, Gujarat 360001',
    'pincode': '360001',
    'contactNumber': '0281-2458331',
    'phone': '0281-2458331',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 22.3039, 'lng': 70.8022},
    'latitude': 22.3039,
    'longitude': 70.8022,
    'location': {'type': 'Point', 'coordinates': [70.8022, 22.3039]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 12,
    'totalBeds': 850,
    'availableBeds': 110,
    'icuBedsTotal': 75,
    'icuBedsAvailable': 18,
    'specialties': ['General Medicine', 'Cardiology', 'Orthopedics', 'General Surgery', 'Pediatrics']
  },
  {
    'id': 'fac_raj_gondal_02',
    'facilityId': 'fac_raj_gondal_02',
    'name': 'Gondal Sub-District Hospital',
    'type': 'SUB_DISTRICT_HOSPITAL',
    'district': 'Rajkot',
    'state': 'Gujarat',
    'address': 'Gondal Bypass, Gondal, Rajkot - 360311',
    'pincode': '360311',
    'contactNumber': '02825-220145',
    'phone': '02825-220145',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 21.9619, 'lng': 70.7997},
    'latitude': 21.9619,
    'longitude': 70.7997,
    'location': {'type': 'Point', 'coordinates': [70.7997, 21.9619]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 10,
    'totalBeds': 120,
    'availableBeds': 24,
    'icuBedsTotal': 10,
    'icuBedsAvailable': 3,
    'specialties': ['General Medicine', 'Pediatrics', 'Maternal Health']
  },
  {
    'id': 'fac_ahd_civil_01',
    'facilityId': 'fac_ahd_civil_01',
    'name': 'Ahmedabad Civil Hospital & BJ Medical College',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Ahmedabad',
    'state': 'Gujarat',
    'address': 'Civil Hospital Campus, Asarwa, Ahmedabad - 380016',
    'pincode': '380016',
    'contactNumber': '079-2268-0074',
    'phone': '079-2268-0074',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.0528, 'lng': 72.5930},
    'latitude': 23.0528,
    'longitude': 72.5930,
    'location': {'type': 'Point', 'coordinates': [72.5930, 23.0528]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 15,
    'totalBeds': 2800,
    'availableBeds': 180,
    'icuBedsTotal': 200,
    'icuBedsAvailable': 35,
    'specialties': ['Cardiology', 'Neurology', 'Oncology', 'General Medicine', 'Trauma & Emergency']
  },
  {
    'id': 'fac_un_mehta',
    'facilityId': 'fac_un_mehta',
    'name': 'U. N. Mehta Institute of Cardiology & Research Centre',
    'type': 'SPECIALTY_HOSPITAL',
    'district': 'Ahmedabad',
    'state': 'Gujarat',
    'address': 'Civil Hospital Campus, Asarwa, Ahmedabad - 380016',
    'pincode': '380016',
    'contactNumber': '079-2268-4200',
    'phone': '079-2268-4200',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.0524, 'lng': 72.5932},
    'latitude': 23.0524,
    'longitude': 72.5932,
    'location': {'type': 'Point', 'coordinates': [72.5932, 23.0524]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 10,
    'totalBeds': 1251,
    'availableBeds': 142,
    'icuBedsTotal': 180,
    'icuBedsAvailable': 34,
    'specialties': ['Cardiology', 'Cardiac Surgery', 'Interventional Cardiology', 'Pediatric Cardiology', 'Cath Lab']
  },
  {
    'id': 'fac_ahd_sola_02',
    'facilityId': 'fac_ahd_sola_02',
    'name': 'GMERS Medical College & Civil Hospital Sola',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Ahmedabad',
    'state': 'Gujarat',
    'address': 'SG Highway, Sola, Ahmedabad - 380060',
    'pincode': '380060',
    'contactNumber': '079-2766-1212',
    'phone': '079-2766-1212',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 23.0825, 'lng': 72.5284},
    'latitude': 23.0825,
    'longitude': 72.5284,
    'location': {'type': 'Point', 'coordinates': [72.5284, 23.0825]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 18,
    'totalBeds': 750,
    'availableBeds': 75,
    'icuBedsTotal': 50,
    'icuBedsAvailable': 10,
    'specialties': ['General Medicine', 'General Surgery', 'Orthopedics', 'Pediatrics', 'Obstetrics & Gynecology']
  },
  {
    'id': 'fac_ahd_lg_03',
    'facilityId': 'fac_ahd_lg_03',
    'name': 'LG Municipal General Hospital',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Ahmedabad',
    'state': 'Gujarat',
    'address': 'Maninagar, Ahmedabad - 380008',
    'pincode': '380008',
    'contactNumber': '079-2546-1380',
    'phone': '079-2546-1380',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 22.9985, 'lng': 72.6025},
    'latitude': 22.9985,
    'longitude': 72.6025,
    'location': {'type': 'Point', 'coordinates': [72.6025, 22.9985]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 20,
    'totalBeds': 800,
    'availableBeds': 54,
    'icuBedsTotal': 60,
    'icuBedsAvailable': 8,
    'specialties': ['General Medicine', 'Surgery', 'Orthopedics', 'Cardiology', 'Pediatrics']
  },
  {
    'id': 'fac_surat_civil_01',
    'facilityId': 'fac_surat_civil_01',
    'name': 'New Civil Hospital Surat (Govt Medical College)',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Surat',
    'state': 'Gujarat',
    'address': 'Majura Gate, Surat - 395001',
    'pincode': '395001',
    'contactNumber': '0261-2244175',
    'phone': '0261-2244175',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 21.1702, 'lng': 72.8311},
    'latitude': 21.1702,
    'longitude': 72.8311,
    'location': {'type': 'Point', 'coordinates': [72.8311, 21.1702]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 14,
    'totalBeds': 780,
    'availableBeds': 110,
    'icuBedsTotal': 65,
    'icuBedsAvailable': 15,
    'specialties': ['General Medicine', 'General Surgery', 'Pediatrics', 'Obstetrics & Gynecology']
  },
  {
    'id': 'fac_vad_ssg_01',
    'facilityId': 'fac_vad_ssg_01',
    'name': 'SSG Hospital & Medical College Vadodara',
    'type': 'DISTRICT_HOSPITAL',
    'district': 'Vadodara',
    'state': 'Gujarat',
    'address': 'Jail Road, Sayajiganj, Vadodara - 390001',
    'pincode': '390001',
    'contactNumber': '0265-2424848',
    'phone': '0265-2424848',
    'emergencyNumber': '108',
    'emergencyPhone': '108',
    'coordinates': {'lat': 22.3129, 'lng': 73.1895},
    'latitude': 22.3129,
    'longitude': 73.1895,
    'location': {'type': 'Point', 'coordinates': [73.1895, 22.3129]},
    'isOpen': True,
    'isActive': True,
    'isVerified': True,
    'emergencyAvailable': True,
    'currentWaitTimeMinutes': 15,
    'totalBeds': 1200,
    'availableBeds': 130,
    'icuBedsTotal': 90,
    'icuBedsAvailable': 20,
    'specialties': ['General Medicine', 'Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics']
  }
]

for h in all_hospitals:
    db.hospitals.update_one({'id': h['id']}, {'$set': h}, upsert=True)
    db.facilities.update_one({'id': h['id']}, {'$set': h}, upsert=True)

print(f"Successfully synced {len(all_hospitals)} hospitals across Gujarat into MongoDB healthcare_db!")
